/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteRouteImport } from './routes/painel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelQualidadeRouteImport } from './routes/painel/qualidade'
import { Route as PainelOwnershipRouteImport } from './routes/painel/ownership'
import { Route as PainelImpactoRouteImport } from './routes/painel/impacto'
import { Route as PainelDeliveryRouteImport } from './routes/painel/delivery'
import { Route as PainelComunicacaoRouteImport } from './routes/painel/comunicacao'
import { Route as PainelCompromissoRouteImport } from './routes/painel/compromisso'

const PainelRouteRoute = PainelRouteRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelQualidadeRoute = PainelQualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelOwnershipRoute = PainelOwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelImpactoRoute = PainelImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelDeliveryRoute = PainelDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelComunicacaoRoute = PainelComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => PainelRouteRoute,
} as any)
const PainelCompromissoRoute = PainelCompromissoRouteImport.update({
  id: '/compromisso',
  path: '/compromisso',
  getParentRoute: () => PainelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/painel/compromisso': typeof PainelCompromissoRoute
  '/painel/comunicacao': typeof PainelComunicacaoRoute
  '/painel/delivery': typeof PainelDeliveryRoute
  '/painel/impacto': typeof PainelImpactoRoute
  '/painel/ownership': typeof PainelOwnershipRoute
  '/painel/qualidade': typeof PainelQualidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/painel/compromisso': typeof PainelCompromissoRoute
  '/painel/comunicacao': typeof PainelComunicacaoRoute
  '/painel/delivery': typeof PainelDeliveryRoute
  '/painel/impacto': typeof PainelImpactoRoute
  '/painel/ownership': typeof PainelOwnershipRoute
  '/painel/qualidade': typeof PainelQualidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteRouteWithChildren
  '/painel/compromisso': typeof PainelCompromissoRoute
  '/painel/comunicacao': typeof PainelComunicacaoRoute
  '/painel/delivery': typeof PainelDeliveryRoute
  '/painel/impacto': typeof PainelImpactoRoute
  '/painel/ownership': typeof PainelOwnershipRoute
  '/painel/qualidade': typeof PainelQualidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/painel/compromisso'
    | '/painel/comunicacao'
    | '/painel/delivery'
    | '/painel/impacto'
    | '/painel/ownership'
    | '/painel/qualidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/painel'
    | '/painel/compromisso'
    | '/painel/comunicacao'
    | '/painel/delivery'
    | '/painel/impacto'
    | '/painel/ownership'
    | '/painel/qualidade'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/painel/compromisso'
    | '/painel/comunicacao'
    | '/painel/delivery'
    | '/painel/impacto'
    | '/painel/ownership'
    | '/painel/qualidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRouteRoute: typeof PainelRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/qualidade': {
      id: '/painel/qualidade'
      path: '/qualidade'
      fullPath: '/painel/qualidade'
      preLoaderRoute: typeof PainelQualidadeRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/ownership': {
      id: '/painel/ownership'
      path: '/ownership'
      fullPath: '/painel/ownership'
      preLoaderRoute: typeof PainelOwnershipRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/impacto': {
      id: '/painel/impacto'
      path: '/impacto'
      fullPath: '/painel/impacto'
      preLoaderRoute: typeof PainelImpactoRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/delivery': {
      id: '/painel/delivery'
      path: '/delivery'
      fullPath: '/painel/delivery'
      preLoaderRoute: typeof PainelDeliveryRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/comunicacao': {
      id: '/painel/comunicacao'
      path: '/comunicacao'
      fullPath: '/painel/comunicacao'
      preLoaderRoute: typeof PainelComunicacaoRouteImport
      parentRoute: typeof PainelRouteRoute
    }
    '/painel/compromisso': {
      id: '/painel/compromisso'
      path: '/compromisso'
      fullPath: '/painel/compromisso'
      preLoaderRoute: typeof PainelCompromissoRouteImport
      parentRoute: typeof PainelRouteRoute
    }
  }
}

interface PainelRouteRouteChildren {
  PainelCompromissoRoute: typeof PainelCompromissoRoute
  PainelComunicacaoRoute: typeof PainelComunicacaoRoute
  PainelDeliveryRoute: typeof PainelDeliveryRoute
  PainelImpactoRoute: typeof PainelImpactoRoute
  PainelOwnershipRoute: typeof PainelOwnershipRoute
  PainelQualidadeRoute: typeof PainelQualidadeRoute
}

const PainelRouteRouteChildren: PainelRouteRouteChildren = {
  PainelCompromissoRoute: PainelCompromissoRoute,
  PainelComunicacaoRoute: PainelComunicacaoRoute,
  PainelDeliveryRoute: PainelDeliveryRoute,
  PainelImpactoRoute: PainelImpactoRoute,
  PainelOwnershipRoute: PainelOwnershipRoute,
  PainelQualidadeRoute: PainelQualidadeRoute,
}

const PainelRouteRouteWithChildren = PainelRouteRoute._addFileChildren(
  PainelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRouteRoute: PainelRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
